wandb_version: 1

wandb_api_key:
  desc: null
  value: 6b305360cd440b1f7432d6f1ba4d81e0c0a60536
wandb_project:
  desc: null
  value: palette_scene2scene
name:
  desc: null
  value: train_uncropping_test
gpu_ids:
  desc: null
  value:
  - 0
seed:
  desc: null
  value: -1
finetune_norm:
  desc: null
  value: false
path:
  desc: null
  value:
    base_dir: /media/seven/HD_12/code/Palette/experiments
    code: /media/seven/HD_12/code/Palette/experiments/train_uncropping_test_230903_195349/code
    tb_logger: /media/seven/HD_12/code/Palette/experiments/train_uncropping_test_230903_195349/tb_logger
    results: /media/seven/HD_12/code/Palette/experiments/train_uncropping_test_230903_195349/results
    checkpoint: /media/seven/HD_12/code/Palette/experiments/train_uncropping_test_230903_195349/checkpoint
    resume_state: null
    experiments_root: /media/seven/HD_12/code/Palette/experiments/train_uncropping_test_230903_195349
datasets:
  desc: null
  value:
    train:
      which_dataset:
        name:
        - data.dataset
        - UncroppingDataset
        args:
          data_root: /media/seven/HD_12/data/palette_data/test/day
          data_len: -1
          mask_config:
            mask_mode: hybrid
      dataloader:
        validation_split: 2
        args:
          batch_size: 3
          num_workers: 4
          shuffle: true
          pin_memory: true
          drop_last: true
        val_args:
          batch_size: 1
          num_workers: 4
          shuffle: false
          pin_memory: true
          drop_last: false
    test:
      which_dataset:
        name: UncroppingDataset
        args:
          data_root: /media/seven/HD_12/data/palette_data/test/night
          mask_config:
            mask_mode: onedirection
            shape: []
      dataloader:
        args:
          batch_size: 8
          num_workers: 4
          pin_memory: true
model:
  desc: null
  value:
    which_model:
      name:
      - models.model
      - Palette
      args:
        sample_num: 8
        task: uncropping
        ema_scheduler:
          ema_start: 1
          ema_iter: 1
          ema_decay: 0.9999
        optimizers:
        - lr: 5.0e-05
          weight_decay: 0
    which_networks:
    - name:
      - models.network
      - Network
      args:
        init_type: kaiming
        module_name: guided_diffusion
        unet:
          in_channel: 6
          out_channel: 3
          inner_channel: 64
          channel_mults:
          - 1
          - 2
          - 4
          - 8
          attn_res:
          - 16
          num_head_channels: 32
          res_blocks: 2
          dropout: 0.2
          image_size: 256
        beta_schedule:
          train:
            schedule: linear
            n_timestep: 2000
            linear_start: 1.0e-06
            linear_end: 0.01
          test:
            schedule: linear
            n_timestep: 1000
            linear_start: 0.0001
            linear_end: 0.09
    which_optimizers:
    - name: Adam
      args:
        lr: 5.0e-05
        weight_decay: 0
    which_lr_schedulers:
    - {}
    which_losses:
    - mse_loss
    which_metrics:
    - mae
train:
  desc: null
  value:
    n_epoch: 100000000.0
    n_iter: 100000000.0
    val_epoch: 1
    save_checkpoint_epoch: 1
    log_iter: 10000.0
    tensorboard: true
debug:
  desc: null
  value:
    val_epoch: 1
    save_checkpoint_epoch: 1
    log_iter: 10
    debug_split: 50
phase:
  desc: null
  value: train
distributed:
  desc: null
  value: false
world_size:
  desc: null
  value: 1
local_rank:
  desc: null
  value: 0
global_rank:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693742030.83338
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 34
      4: 3.7.6
      5: 0.15.3
      8:
      - 5
